### PR TITLE
FIX: fixing the issue with NaN values read from Excel

### PR DESCRIPTION
**Pull request by mrakitin**
Per our conversation in emails.

### CODE REVIEW

**Review by awalter-bnl — APPROVED** [review]
This looks like a simple and easy fix to the problem. It is OK by me.

**Comment by tacaswell** [comment]
Do we know what input in the spread sheet is causing the nan?  Do we care?

**Review by tacaswell — APPROVED** [review]

**Comment by awalter-bnl** [comment]
@tacaswell I don't think we care. The spreadsheet is used so that users can input information about what scans to run. At some point they will (accidently or on purpose) enter NAN in areas of the spreadsheet that do no break the code. I think we should just assume the code will throw an exception if it can't handle the NAN.

**Comment by mrakitin** [comment]
That's how the file looks like:
ios

And here is how pandas reads it in:
```
$ ipython
Python 3.6.4 |Anaconda, Inc.| (default, Dec 21 2017, 15:39:08)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.
 
In [1]: import pandas
 
In [2]: f = pandas.read_excel('sample_list.xlsx')
 
In [3]: f
Out[3]:
  sample_index       name    pos interesting_edges
0      sample1   S1CuZSM5  250.0               O_K
1      sample2   S3CuZSM5  254.0               O_K
2      sample3   S5CuZSM5  260.0               O_K
3      sample4  S10CuZSM5  265.0               O_K
4      sample5    NiCeO21  274.0               O_K
5      sample6  TiO2Co3O4  278.0               O_K
6      sample7    NiCeO22  280.9               O_K
7      sample8     TiO2Co  283.7               O_K
8          NaN        NaN    NaN               NaN

```

**Review by irawaluyo — APPROVED** [review]

**Review by danielballan — APPROVED** [review]

**Pull request merged**
